apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-service
  description: |
        A short description as a display text.
  tags:
    - business
spec:
  type: service
  owner: team-moneypenny
  lifecycle: production
  system: my-system
  providesApis:
    - my-service-api
  consumesApis:
    - other-service-api